### ISSUE TITLE
Link to the plugin or theme in the directory

### ISSUE THREAD

**Issue by johnbillion** [wpdirectory/wpdir#14]
From a search result, it doesn't appear to be possible to navigate straight to the plugin or theme in the corresponding directory on wordpress.org. This would be handy!

**Comment by PeterBooker** [comment]
Thank you for the suggestion. I am working on an update to the search page UI at the moment, so this is perfect timing.

Can I ask what you would be looking to do after navigating to the wordpress.org page? I have just been considering a modal with an overview of the Plugin or Theme page, using data from the wp.org API. Would that be sufficient, or does it need to be the wordpress.org page? Likewise, if there are valid needs for the wordpress.org page perhaps I should avoid my own modal with Plugin/Theme data completely and just give a direct link?

**Comment by johnbillion** [comment]
My use case is that a result appeared in a plugin with a really long name and I was unable to copy and paste it from the results list (I think there's an open/close toggle handler that prevents text selection on the plugin name), thus I had to manually type the plugin name into a Google search :-)

I think linking straight to the w.org directory makes the most sense. The user gains the advantage of being able to access the support forum, the reviews, and the items in the Development tab such as links to the SVN repo etc.

**Comment by PeterBooker** [comment]
Ah, that is excellent thank you. I think that illustrates the need for a direct wp.org link perfectly. I will add that into the UI re-work and comment again once it is live.

*(edit: I will also look at not being able to see and/or copy the Plugin/Theme names when they are longer, as that makes it very difficult to use.)*

**Comment by PeterBooker** [comment]
Hi John, sorry for the long delay. The current version has a wp.org link as an icon before the plugin/theme name. I am still not entirely content with this but, frustratingly, after working through three other versions of the search page they all ended up more confusing/cluttered so I scrapped them. I also made a few fixes so that the output displays better on smaller screens to make it less likely that seeing the name is an issue.

I still intend on redesigning the search page, I just need to find the right UI. I will keep this issue open until I have implemented a better search page UI.
