### ISSUE TITLE
Search is not working on live site

### ISSUE THREAD

**Issue by ethicalhack3r** [wpdirectory/wpdir#32]
When performing a search on https://wpdirectory.net/ the red loading bar reaches the end but no results are shown.

**Comment by PeterBooker** [comment]
Hi ethicalhack3r,

Thanks for the note. I am aware but have had a work deadline that I had to meet (tomorrow) which has eaten up all my free time. I will be focused on fixing wpdir from Friday and I am sure it will be working again before next week.

Sorry for the inconvenience. I would have much rathered this was resolved straight away, the timing has just been dreadful.

**Comment by ethicalhack3r** [comment]
Hi Peter,

Thanks for your response. I completely understand, I've been in the exact same position in the past more than once.

Thanks for creating wpdir I've found it very useful on a few occasions.

Let me know if there's anything I, or WPScan, can do to help, in any way. Whether that be sponsorship, hosting, whatever. And we can see if we can help.

Thanks,
Ryan

**Comment by PeterBooker** [comment]
The service is back up now, sorry for such a long period of downtime.

Resolving the initial hosting config issue only highlighted other problems, resulting in my finally having to host it on a Windows computer locally. There is some issue with the use of mmap which is not working on any version of Linux I have tried.

I will continue working on it until I can get it back to being hosted normally. I should have resorted to this local hosting earlier, I have made a note for myself.

**Comment by ethicalhack3r** [comment]
Awesome, thanks Peter!

Is there any way WPScan can help? Sponsorship maybe?

**Comment by PeterBooker** [comment]
The offer is very kind, Ryan. I believe I have all the resources needed- working on it has reminded me that I only took a break to improve my React (this was my first React site), so that I could create a much better interface.

Between the experience of the weaknesses of the first version and using React at work I have everything I need to focus on version 2 now. A more robust and long-term sustainable infrastructure is priority number one.

I would hugely appreciate any feedback, requests and/or stories about how you use wpdir though.
