### ISSUE TITLE
Live site 502 error

### ISSUE THREAD

**Issue by gagan0123** [wpdirectory/wpdir#40]
The live site hosted at https://wpdirectory.net/ is currently inaccessible and giving `502 Bad Gateway` error

![image](https://github.com/wpdirectory/wpdir/assets/1535505/ca04ffa6-0df1-41db-9808-d712355b51ec)

**Comment by gagan0123** [comment]
The service is up and running again, so closing this issue

**Comment by gagan0123** [comment]
The issue is back again, so re-opening this issue

**Comment by PeterBooker** [comment]
Unfortunately the process is intermittently erroring when it runs out of available memory, which is frustrating as it is already running on a 32GB VPS.

I found a bug in the systemd config causing it not to restart properly on errors. So hopefully it will restart automatically when it errors now.

However, longer term I need to improve the memory usage so that 32GB is enough to work with.

**Comment by johnbillion** [comment]
Been seeing this a few times again today.

**Comment by carstingaxion** [comment]
Unfortunately, I have seen this on all my attempts in the last days.

**Comment by PeterBooker** [comment]
@carstingaxion Unfortunately the service is now crashing with `fatal error: runtime: out of memory`, however the VPS it runs on has just been upgraded from 32GB to 64GB and it still happens. So it is possibly something internal related to memory allocation.

I will try to fix it as soon as I can, but it might take me a while to troubleshoot and fix this.

Sorry for any inconvenience.

**Comment by PeterBooker** [comment]
I believe that some stability has been achieved. It has been running for over 24 hours now.

I made some OS level tweaks, like setting `/proc/sys/vm/overcommit_memory` to `1`, and increased ther VPS resources. However, I am not certain what the problem was and why it is (seemingly) now resolved.

Please let me know if you notice any more problems!

**Comment by gagan0123** [comment]
Thanks @PeterBooker 🙂 

Closing the issue as the site is now up again.
